spring:
  application:
    name: usertraining
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/training-user?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: "classpath*:data.sql"
      mode: always
  mail:
    properties:
      mail.smtp.ssl.trust: "*"
mailtrap:
  api-url: https://sandbox.api.mailtrap.io/api/send/2192121
  api-token: e5bfc9d1c956f8abac925b4bbf2a0103
  from-email: no-reply@expediteur.com


